# Generated by Django 4.0.5 on 2024-05-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem_id', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=5)),
            ],
        ),
    ]
