# Generated by Django 4.0.5 on 2024-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
