# Generated by Django 4.0.5 on 2024-05-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0004_user_handles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_handles',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_handles',
            name='handle',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
